# Build stage
FROM node:18-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

ARG REACT_APP_RASA_URL
ARG REACT_APP_PLANT_API_URL

ENV REACT_APP_RASA_URL=$REACT_APP_RASA_URL
ENV REACT_APP_PLANT_API_URL=$REACT_APP_PLANT_API_URL

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
